In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import pandas as pd
import os

base_path = '/content/drive/MyDrive/final-cv-term/samm/densenet'
csvPath = os.path.sep.join([base_path,
  "{}.csv".format('test-exp-features-densenet_samm_')])
#csvFile = open(csvPath, "w")

#writer = csv.writer(csvFile)
features_list = ['Label']
features_list.append('Image');
for i in range(1000):
  features_list.append('F' + str(i));

df = pd.read_csv(csvPath,names=features_list)
df = df.dropna(axis=0, how='any', thresh=None, subset=None, inplace=False)

In [3]:
df.head(5)

Label                            Image  ...      F998      F999
0  Anger  Anger_006_006_1_2_006_05578.jpg  ... -8.471697 -4.171546
1  Anger  Anger_006_006_1_2_006_05580.jpg  ... -8.847574 -3.819736
2  Anger  Anger_006_006_1_2_006_05568.jpg  ... -8.988487 -4.088883
3  Anger  Anger_006_006_1_2_006_05598.jpg  ... -9.046871 -3.835012
4  Anger  Anger_006_006_1_2_006_05603.jpg  ... -9.322181 -3.232673

[5 rows x 1002 columns]

In [4]:
print(features_list)
print('after\n')
features_labels = features_list[2:]
print(features_labels)

['Label', 'Image', 'F0', 'F1', 'F2', 'F3', 'F4', 'F5', 'F6', 'F7', 'F8', 'F9', 'F10', 'F11', 'F12', 'F13', 'F14', 'F15', 'F16', 'F17', 'F18', 'F19', 'F20', 'F21', 'F22', 'F23', 'F24', 'F25', 'F26', 'F27', 'F28', 'F29', 'F30', 'F31', 'F32', 'F33', 'F34', 'F35', 'F36', 'F37', 'F38', 'F39', 'F40', 'F41', 'F42', 'F43', 'F44', 'F45', 'F46', 'F47', 'F48', 'F49', 'F50', 'F51', 'F52', 'F53', 'F54', 'F55', 'F56', 'F57', 'F58', 'F59', 'F60', 'F61', 'F62', 'F63', 'F64', 'F65', 'F66', 'F67', 'F68', 'F69', 'F70', 'F71', 'F72', 'F73', 'F74', 'F75', 'F76', 'F77', 'F78', 'F79', 'F80', 'F81', 'F82', 'F83', 'F84', 'F85', 'F86', 'F87', 'F88', 'F89', 'F90', 'F91', 'F92', 'F93', 'F94', 'F95', 'F96', 'F97', 'F98', 'F99', 'F100', 'F101', 'F102', 'F103', 'F104', 'F105', 'F106', 'F107', 'F108', 'F109', 'F110', 'F111', 'F112', 'F113', 'F114', 'F115', 'F116', 'F117', 'F118', 'F119', 'F120', 'F121', 'F122', 'F123', 'F124', 'F125', 'F126', 'F127', 'F128', 'F129', 'F130', 'F131', 'F132', 'F133', 'F134', 'F135', 'F1

In [5]:
print(df['Label'])

0           Anger
1           Anger
2           Anger
3           Anger
4           Anger
           ...   
11811    Contempt
11812    Contempt
11813    Contempt
11814    Contempt
11815    Contempt
Name: Label, Length: 11816, dtype: object


In [6]:
from sklearn.preprocessing import StandardScaler

df2 = df[2:]
# Separating out the features
x = df.loc[:, features_labels].values
print(x)
# Separating out the target
y = df.loc[:,['Label']].values
# Standardizing the features
x = StandardScaler().fit_transform(x)


[[-6.853187   -6.9778724   0.49582887 ...  9.086105   -8.471697
  -4.1715455 ]
 [-7.2210264  -6.745644    0.18517613 ...  9.40253    -8.847574
  -3.8197355 ]
 [-7.1319075  -6.7650375   0.7874225  ...  8.8520155  -8.988487
  -4.088883  ]
 ...
 [ 0.60819745 -7.1952443   5.2043905  ... 14.081104   -7.779313
  -5.649283  ]
 [-1.2000618  -7.882557    6.9030247  ... 15.951872   -9.612621
  -4.438604  ]
 [-0.46338677 -6.7454357   3.716115   ... 15.193262   -8.204946
  -5.431808  ]]


In [7]:
from sklearn.decomposition import PCA
import numpy as np
pca = PCA(n_components=5)
principalComponents = pca.fit_transform(x)
principalDf = pd.DataFrame(data = principalComponents)

principalDf.reset_index(drop=True, inplace=True)
df['Label'].reset_index(drop=True, inplace=True)

finalDf = pd.concat([principalDf, df['Label']], axis=1)

finalDf.tail(20)

0         1          2          3          4     Label
11796  3.797549  5.730752 -15.283052  14.396458  29.304085  Contempt
11797  3.663772  5.955721 -15.435811  14.089652  28.718331  Contempt
11798  4.000204  6.584276 -15.726225  14.232232  29.396105  Contempt
11799  4.098095  6.523476 -15.798197  14.460820  29.465223  Contempt
11800  3.315071  6.581495 -15.116871  13.850392  28.378189  Contempt
11801  3.870462  6.516632 -15.645469  14.086008  29.233905  Contempt
11802  4.289550  6.444143 -15.616071  14.261365  29.641822  Contempt
11803  3.897240  6.962867 -15.879598  14.177179  29.061125  Contempt
11804  3.542147  6.729613 -15.016817  13.831412  28.850094  Contempt
11805  3.679072  6.867393 -15.455207  14.105835  28.611450  Contempt
11806  3.733375  6.924133 -15.524768  14.085563  29.257549  Contempt
11807  3.831327  5.726628 -15.175028  14.380678  29.152379  Contempt
11808  3.431451  6.951446 -15.522864  13.975028  28.647176  Contempt
11809  3.624566  5.565481 -15.193882  14.111854  28.800452  Contempt
11810  3.378881  6.926903 -15.143275  13.934133  28.264941  Contempt
11811  3.342878  7.100757 -15.240857  13.736415  28.413292  Contempt
11812  4.069135  6.591114 -15.714139  14.400589  29.318973  Contempt
11813  3.714416  6.726886 -15.790775  14.034546  29.427977  Contempt
11814  3.494766  6.788470 -15.019114  14.078268  28.785801  Contempt
11815  3.933199  5.758319 -15.069817  14.203635  28.845230  Contempt

In [8]:
#df = df[:2]

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)


from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier(max_depth=2, random_state=0)
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:11: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  # This is added back by InteractiveShellApp.init_path()


In [9]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

cm = confusion_matrix(y_test, y_pred)
print(cm)
print('Accuracy' +str(accuracy_score(y_test, y_pred)))

[[803   0   0   0  35   1   0   0]
 [134   0   0   0  22  10   0   0]
 [ 88   0   0   0  47   0   0   0]
 [ 74   0   0   0  10  14   0   0]
 [ 71   0   0   0 325  15   0   0]
 [205   0   0   0  63 170   0   0]
 [ 85   0   0   0   0   0   0   0]
 [151   0   0   0  40   1   0   0]]
Accuracy0.5490693739424704


In [10]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [11]:
from sklearn.decomposition import PCA

pca = PCA()
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)

cm = confusion_matrix(y_test, y_pred)
print(cm)
print('Accuracy' +str(accuracy_score(y_test, y_pred)))

[[803   0   0   0  35   1   0   0]
 [134   0   0   0  22  10   0   0]
 [ 88   0   0   0  47   0   0   0]
 [ 74   0   0   0  10  14   0   0]
 [ 71   0   0   0 325  15   0   0]
 [205   0   0   0  63 170   0   0]
 [ 85   0   0   0   0   0   0   0]
 [151   0   0   0  40   1   0   0]]
Accuracy0.5490693739424704


In [12]:
from sklearn.pipeline import Pipeline
from sklearn.decomposition import PCA

finalDf.to_csv (base_path+'/exp-pca-features-samm-densnet.csv', index = False, header=True)
