In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [27]:
import pandas as pd
import os

base_path = '/content/drive/MyDrive/final-cv-term/densenet'
csvPath = os.path.sep.join([base_path,
  "{}.csv".format('exp-features-densenet_casmeII_')])
#csvFile = open(csvPath, "w")

#writer = csv.writer(csvFile)
features_list = ['Label']
features_list.append('Image');
for i in range(1000):
  features_list.append('F' + str(i));

df = pd.read_csv(csvPath,names=features_list)
df = df.dropna(axis=0, how='any', thresh=None, subset=None, inplace=False)

In [28]:
df.head(5)

Label                                Image  ...      F998      F999
0  happiness  happiness_01_EP02_01f_reg_img65.jpg  ... -1.394707 -0.257658
1  happiness  happiness_01_EP02_01f_reg_img59.jpg  ... -1.267923 -0.032279
2  happiness  happiness_01_EP02_01f_reg_img47.jpg  ... -1.306296  0.373993
3  happiness  happiness_01_EP02_01f_reg_img57.jpg  ... -1.248153  0.121167
4  happiness  happiness_01_EP02_01f_reg_img64.jpg  ... -1.393961 -0.546497

[5 rows x 1002 columns]

In [29]:
print(features_list)
print('after\n')
features_labels = features_list[2:]
print(features_labels)

['Label', 'Image', 'F0', 'F1', 'F2', 'F3', 'F4', 'F5', 'F6', 'F7', 'F8', 'F9', 'F10', 'F11', 'F12', 'F13', 'F14', 'F15', 'F16', 'F17', 'F18', 'F19', 'F20', 'F21', 'F22', 'F23', 'F24', 'F25', 'F26', 'F27', 'F28', 'F29', 'F30', 'F31', 'F32', 'F33', 'F34', 'F35', 'F36', 'F37', 'F38', 'F39', 'F40', 'F41', 'F42', 'F43', 'F44', 'F45', 'F46', 'F47', 'F48', 'F49', 'F50', 'F51', 'F52', 'F53', 'F54', 'F55', 'F56', 'F57', 'F58', 'F59', 'F60', 'F61', 'F62', 'F63', 'F64', 'F65', 'F66', 'F67', 'F68', 'F69', 'F70', 'F71', 'F72', 'F73', 'F74', 'F75', 'F76', 'F77', 'F78', 'F79', 'F80', 'F81', 'F82', 'F83', 'F84', 'F85', 'F86', 'F87', 'F88', 'F89', 'F90', 'F91', 'F92', 'F93', 'F94', 'F95', 'F96', 'F97', 'F98', 'F99', 'F100', 'F101', 'F102', 'F103', 'F104', 'F105', 'F106', 'F107', 'F108', 'F109', 'F110', 'F111', 'F112', 'F113', 'F114', 'F115', 'F116', 'F117', 'F118', 'F119', 'F120', 'F121', 'F122', 'F123', 'F124', 'F125', 'F126', 'F127', 'F128', 'F129', 'F130', 'F131', 'F132', 'F133', 'F134', 'F135', 'F1

In [30]:
print(df['Label'])

0        happiness
1        happiness
2        happiness
3        happiness
4        happiness
           ...    
17119      sadness
17120      sadness
17121      sadness
17122      sadness
17123      sadness
Name: Label, Length: 17124, dtype: object


In [31]:
from sklearn.preprocessing import StandardScaler

df2 = df[2:]
# Separating out the features
x = df.loc[:, features_labels].values
print(x)
# Separating out the target
y = df.loc[:,['Label']].values
# Standardizing the features
x = StandardScaler().fit_transform(x)


[[-4.5639515   2.0130625   0.05388308 ... -4.7349935  -1.3947074
  -0.257658  ]
 [-3.5260959   1.7684854  -1.1123459  ... -4.5509257  -1.2679226
  -0.03227878]
 [-4.0746613   2.4810715  -0.22494173 ... -4.2253428  -1.3062958
   0.3739934 ]
 ...
 [ 1.1799102  -4.2807226  -5.3057146  ... -5.2964153   2.501129
  -6.174225  ]
 [ 1.2621703  -3.6788962  -5.322913   ... -5.2243114   2.0191426
  -6.694173  ]
 [ 1.2721798  -3.3329556  -5.4277325  ... -5.6386757   2.256784
  -6.156392  ]]


In [32]:
from sklearn.decomposition import PCA
import numpy as np
pca = PCA(n_components=5)
principalComponents = pca.fit_transform(x)
principalDf = pd.DataFrame(data = principalComponents)

principalDf.reset_index(drop=True, inplace=True)
df['Label'].reset_index(drop=True, inplace=True)

finalDf = pd.concat([principalDf, df['Label']], axis=1)

finalDf.tail(20)

0          1          2         3         4    Label
17104  23.546875 -12.615484 -12.855677 -6.563048 -6.746096  sadness
17105  23.601979 -12.269642 -13.379793 -6.659834 -6.911728  sadness
17106  22.631119 -12.636590 -13.024727 -6.161656 -6.510064  sadness
17107  23.545264 -13.492706 -13.296021 -6.202363 -6.630398  sadness
17108  23.313991 -12.843506 -13.090462 -6.771292 -6.574014  sadness
17109  23.571353 -13.280337 -13.628915 -6.384759 -6.365132  sadness
17110  24.362441 -13.400006 -13.529596 -6.594127 -6.460124  sadness
17111  23.319289 -13.313889 -13.250401 -6.635764 -7.051507  sadness
17112  23.013818 -12.982396 -13.373200 -5.851340 -6.651792  sadness
17113  23.747991 -13.099162 -13.178727 -6.229409 -6.505956  sadness
17114  23.079003 -12.389646 -13.091141 -5.998140 -6.454948  sadness
17115  24.259980 -13.437290 -13.445904 -6.706990 -6.402193  sadness
17116  24.154811 -13.081532 -13.321723 -6.567065 -6.438129  sadness
17117  22.898566 -13.351846 -12.637566 -6.628006 -7.059226  sadness
17118  23.566924 -13.016840 -13.044507 -6.112805 -6.415439  sadness
17119  22.925998 -12.764127 -13.047383 -6.089222 -6.449780  sadness
17120  24.366758 -13.006051 -13.335424 -6.183514 -6.162898  sadness
17121  23.555562 -12.439925 -13.366727 -6.613924 -6.300619  sadness
17122  23.727711 -12.525174 -13.279798 -6.601290 -6.548314  sadness
17123  23.898181 -12.753877 -13.363179 -6.437766 -6.535930  sadness

In [37]:
#df = df[:2]

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)


from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier(max_depth=2, random_state=0)
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

In [38]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

cm = confusion_matrix(y_test, y_pred)
print(cm)
print('Accuracy' +str(accuracy_score(y_test, y_pred)))

[[ 470    0    0  379    0    0    0]
 [   1    0    0   11    7    0    0]
 [ 173    0    0  249   55    0    0]
 [ 120    0    0 1137    1    0    0]
 [ 170    0    0   76  201    0    0]
 [  25    0    0    9    0    0    0]
 [  57    0    0  284    0    0    0]]
Accuracy0.5278832116788321


In [39]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [40]:
from sklearn.decomposition import PCA

pca = PCA()
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)

cm = confusion_matrix(y_test, y_pred)
print(cm)
print('Accuracy' +str(accuracy_score(y_test, y_pred)))

[[ 470    0    0  379    0    0    0]
 [   1    0    0   11    7    0    0]
 [ 173    0    0  249   55    0    0]
 [ 120    0    0 1137    1    0    0]
 [ 170    0    0   76  201    0    0]
 [  25    0    0    9    0    0    0]
 [  57    0    0  284    0    0    0]]
Accuracy0.5278832116788321


In [42]:
from sklearn.pipeline import Pipeline
from sklearn.decomposition import PCA

finalDf.to_csv (base_path+'/exp-pca-features-casmeII-densenet.csv', index = False, header=True)
