In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [5]:
import pandas as pd
import os

csvPath = os.path.sep.join(['/content/drive/MyDrive/',
  "{}.csv".format('exp-features-2')])
#csvFile = open(csvPath, "w")

#writer = csv.writer(csvFile)

features_list = ['Label']
for i in range(1000):
  features_list.append('F' + str(i));

df = pd.read_csv(csvPath,names=features_list)
df = df.dropna(axis=0, how='any', thresh=None, subset=None, inplace=False)

In [6]:
df.head(5)

Label        F0        F1  ...      F997      F998      F999
0  happiness -0.437911 -2.268914  ...  0.103221 -0.058346 -0.750163
1  happiness -0.343132 -2.103500  ...  0.172563 -0.432087 -1.072601
2  happiness -0.649374 -2.438913  ...  0.942425 -0.532774 -0.807265
3  happiness -0.526462 -1.825423  ...  0.010560 -1.441027 -1.488853
4  happiness -0.405830 -2.653667  ...  0.198053 -0.956625 -0.964331

[5 rows x 1001 columns]

In [10]:
print(features_list)
print('after\n')
features_labels = features_list[1:]
print(features_labels)

['Label', 'F0', 'F1', 'F2', 'F3', 'F4', 'F5', 'F6', 'F7', 'F8', 'F9', 'F10', 'F11', 'F12', 'F13', 'F14', 'F15', 'F16', 'F17', 'F18', 'F19', 'F20', 'F21', 'F22', 'F23', 'F24', 'F25', 'F26', 'F27', 'F28', 'F29', 'F30', 'F31', 'F32', 'F33', 'F34', 'F35', 'F36', 'F37', 'F38', 'F39', 'F40', 'F41', 'F42', 'F43', 'F44', 'F45', 'F46', 'F47', 'F48', 'F49', 'F50', 'F51', 'F52', 'F53', 'F54', 'F55', 'F56', 'F57', 'F58', 'F59', 'F60', 'F61', 'F62', 'F63', 'F64', 'F65', 'F66', 'F67', 'F68', 'F69', 'F70', 'F71', 'F72', 'F73', 'F74', 'F75', 'F76', 'F77', 'F78', 'F79', 'F80', 'F81', 'F82', 'F83', 'F84', 'F85', 'F86', 'F87', 'F88', 'F89', 'F90', 'F91', 'F92', 'F93', 'F94', 'F95', 'F96', 'F97', 'F98', 'F99', 'F100', 'F101', 'F102', 'F103', 'F104', 'F105', 'F106', 'F107', 'F108', 'F109', 'F110', 'F111', 'F112', 'F113', 'F114', 'F115', 'F116', 'F117', 'F118', 'F119', 'F120', 'F121', 'F122', 'F123', 'F124', 'F125', 'F126', 'F127', 'F128', 'F129', 'F130', 'F131', 'F132', 'F133', 'F134', 'F135', 'F136', 'F13

Label        F0        F1  ...      F997      F998      F999
4  happiness -0.405830 -2.653667  ...  0.198053 -0.956625 -0.964331
5  happiness -0.351555 -3.093083  ...  0.619841 -1.181614 -0.762458
6  happiness -0.511237 -2.372645  ...  0.432924 -0.701747 -0.842939
7  happiness -0.546052 -2.462370  ...  1.007676 -1.013797 -0.651827
8  happiness -0.812804 -2.180523  ...  0.876099 -0.873618 -1.125413

[5 rows x 1001 columns]

In [15]:
print(df['Label'])

4        happiness
5        happiness
6        happiness
7        happiness
8        happiness
           ...    
17119      sadness
17120      sadness
17121      sadness
17122      sadness
17123      sadness
Name: Label, Length: 17120, dtype: object


In [11]:
from sklearn.preprocessing import StandardScaler

# Separating out the features
x = df.loc[:, features_labels].values
print(x)
# Separating out the target
y = df.loc[:,['Label']].values
# Standardizing the features
x = StandardScaler().fit_transform(x)


[[-0.40582967 -2.653667    3.1810482  ...  0.19805288 -0.95662516
  -0.9643313 ]
 [-0.3515547  -3.0930834   3.5210385  ...  0.61984086 -1.1816144
  -0.762458  ]
 [-0.5112374  -2.3726454   3.7509482  ...  0.43292385 -0.70174706
  -0.84293914]
 ...
 [-1.4891568  -0.85357475  1.3419858  ... -0.49444526 -1.2717993
   0.2814641 ]
 [-0.6994233  -1.2799203   0.5725733  ... -1.019282   -2.5909204
  -0.01482588]
 [-0.5432633  -1.4596707   0.85291225 ... -1.8183192  -1.5486474
   0.5042043 ]]


In [24]:
from sklearn.decomposition import PCA
import numpy as np
pca = PCA(n_components=5)
principalComponents = pca.fit_transform(x)
principalDf = pd.DataFrame(data = principalComponents)

principalDf.reset_index(drop=True, inplace=True)
df['Label'].reset_index(drop=True, inplace=True)

finalDf = pd.concat([principalDf, df['Label']], axis=1)

finalDf.tail(20)

0         1          2         3         4    Label
17100 -5.124491  5.371944  12.869737 -3.798263  2.644578  sadness
17101 -6.147597  4.021413  13.034422 -4.240952  0.612441  sadness
17102 -5.321895  3.573420  14.383611 -4.982674  0.076536  sadness
17103 -6.190343  4.437728  13.484049 -4.667297  2.139065  sadness
17104 -6.191849  6.032995  12.830379 -3.354538  1.776141  sadness
17105 -5.998023  4.546613  13.543805 -4.177502  1.989924  sadness
17106 -6.890359  5.523734  14.676041 -3.319304  1.500046  sadness
17107 -5.533386  5.175220  12.734791 -3.051674  2.225451  sadness
17108 -6.040764  5.382244  13.256845 -3.134395  2.335330  sadness
17109 -6.240552  3.761951  13.798555 -4.216257  0.934956  sadness
17110 -5.850714  5.431789  13.559118 -2.794429  2.161563  sadness
17111 -5.522784  5.096254  14.053170 -4.213533  2.215263  sadness
17112 -7.447822  5.046788  14.762326 -3.047085  1.266669  sadness
17113 -7.391671  5.588756  14.645291 -5.149656  0.584432  sadness
17114 -5.911156  5.395511  13.422871 -3.204682  2.374379  sadness
17115 -6.490396  5.782597  14.018077 -3.819723  1.681928  sadness
17116 -6.459431  4.967608  13.429802 -3.262131  2.082465  sadness
17117 -6.547368  4.235843  13.635747 -3.069200  2.400899  sadness
17118 -6.829437  4.805091  13.076928 -4.224053  2.666615  sadness
17119 -4.812255  4.408155  13.797355 -3.184366  1.404180  sadness

In [25]:
X = df.drop('Label', 1)
y = df['Label']
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)


from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier(max_depth=2, random_state=0)
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

In [26]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

cm = confusion_matrix(y_test, y_pred)
print(cm)
print('Accuracy' +str(accuracy_score(y_test, y_pred)))

[[ 195    0    0  671    0    0    0]
 [   0    0    0   22    0    0    0]
 [  78    0    0  397    1    0    0]
 [  28    0    0 1234    0    0    0]
 [ 113    0    0  314    1    0    0]
 [  13    0    0   16    0    0    0]
 [   1    0    0  340    0    0    0]]
Accuracy0.41764018691588783


In [27]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [28]:
from sklearn.decomposition import PCA

pca = PCA()
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)

cm = confusion_matrix(y_test, y_pred)
print(cm)
print('Accuracy' +str(accuracy_score(y_test, y_pred)))

[[ 195    0    0  671    0    0    0]
 [   0    0    0   22    0    0    0]
 [  78    0    0  397    1    0    0]
 [  28    0    0 1234    0    0    0]
 [ 113    0    0  314    1    0    0]
 [  13    0    0   16    0    0    0]
 [   1    0    0  340    0    0    0]]
Accuracy0.41764018691588783


In [32]:
from sklearn.pipeline import Pipeline
from sklearn.decomposition import PCA

finalDf.to_csv ('/content/drive/MyDrive/final-cv-term/exp-pca-features-casmeII-resnet50.csv', index = False, header=True)
