In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import pandas as pd
import os

base_path = '/content/drive/MyDrive/final-cv-term/SMIC/resnet50'
csvPath = os.path.sep.join([base_path,
  "{}.csv".format('resnet50_test-exp-features-resnet50_smic_')])
#csvFile = open(csvPath, "w")

#writer = csv.writer(csvFile)
features_list = ['Label']
features_list.append('Image');
for i in range(1000):
  features_list.append('F' + str(i));

df = pd.read_csv(csvPath,names=features_list)
df = df.dropna(axis=0, how='any', thresh=None, subset=None, inplace=False)

In [3]:
df.head(5)

Label     Image        F0  ...      F997      F998      F999
0  positive  2574.jpg  0.207576  ...  1.571547  2.293341 -4.728865
1  positive  2682.jpg  0.243447  ...  2.825051  0.781343 -4.186844
2  positive  2582.jpg -0.350829  ...  1.608617  2.314876 -3.456754
3  positive  3469.jpg  2.944579  ...  3.904832 -0.823104 -3.231838
4  positive  3659.jpg  1.140379  ...  1.896066 -0.693643 -3.559817

[5 rows x 1002 columns]

In [4]:
print(features_list)
print('after\n')
features_labels = features_list[2:]
print(features_labels)

['Label', 'Image', 'F0', 'F1', 'F2', 'F3', 'F4', 'F5', 'F6', 'F7', 'F8', 'F9', 'F10', 'F11', 'F12', 'F13', 'F14', 'F15', 'F16', 'F17', 'F18', 'F19', 'F20', 'F21', 'F22', 'F23', 'F24', 'F25', 'F26', 'F27', 'F28', 'F29', 'F30', 'F31', 'F32', 'F33', 'F34', 'F35', 'F36', 'F37', 'F38', 'F39', 'F40', 'F41', 'F42', 'F43', 'F44', 'F45', 'F46', 'F47', 'F48', 'F49', 'F50', 'F51', 'F52', 'F53', 'F54', 'F55', 'F56', 'F57', 'F58', 'F59', 'F60', 'F61', 'F62', 'F63', 'F64', 'F65', 'F66', 'F67', 'F68', 'F69', 'F70', 'F71', 'F72', 'F73', 'F74', 'F75', 'F76', 'F77', 'F78', 'F79', 'F80', 'F81', 'F82', 'F83', 'F84', 'F85', 'F86', 'F87', 'F88', 'F89', 'F90', 'F91', 'F92', 'F93', 'F94', 'F95', 'F96', 'F97', 'F98', 'F99', 'F100', 'F101', 'F102', 'F103', 'F104', 'F105', 'F106', 'F107', 'F108', 'F109', 'F110', 'F111', 'F112', 'F113', 'F114', 'F115', 'F116', 'F117', 'F118', 'F119', 'F120', 'F121', 'F122', 'F123', 'F124', 'F125', 'F126', 'F127', 'F128', 'F129', 'F130', 'F131', 'F132', 'F133', 'F134', 'F135', 'F1

In [5]:
print(df['Label'])

0       positive
1       positive
2       positive
3       positive
4       positive
          ...   
5221    surprise
5222    surprise
5223    surprise
5224    surprise
5225    surprise
Name: Label, Length: 5226, dtype: object


In [6]:
from sklearn.preprocessing import StandardScaler

df2 = df[2:]
# Separating out the features
x = df.loc[:, features_labels].values
print(x)
# Separating out the target
y = df.loc[:,['Label']].values
# Standardizing the features
x = StandardScaler().fit_transform(x)


[[ 0.20757592  1.6399395  -1.8848938  ...  1.5715474   2.2933407
  -4.7288647 ]
 [ 0.24344695  1.2798293   0.49220657 ...  2.8250508   0.78134274
  -4.186844  ]
 [-0.35082936  1.1782889  -1.0809481  ...  1.6086172   2.3148758
  -3.4567544 ]
 ...
 [ 0.8035266   2.5919116   1.0111864  ...  0.5142442   0.8151847
  -5.6904593 ]
 [ 1.9115796   1.1765591   0.11378908 ...  2.5590165   2.005948
  -3.8361115 ]
 [-1.7990696   1.2776334  -1.0627062  ... -0.58209866  2.5309494
  -5.688023  ]]


In [7]:
from sklearn.decomposition import PCA
import numpy as np
pca = PCA(n_components=5)
principalComponents = pca.fit_transform(x)
principalDf = pd.DataFrame(data = principalComponents)

principalDf.reset_index(drop=True, inplace=True)
df['Label'].reset_index(drop=True, inplace=True)

finalDf = pd.concat([principalDf, df['Label']], axis=1)

finalDf.tail(20)

0          1          2          3          4     Label
5206  -2.005464  -0.036319  -5.157668  -2.703696  11.236761  surprise
5207  -8.924766  -4.765266 -11.838007   0.801583  20.198605  surprise
5208  -1.815263   1.338234  -6.518818  -3.268318   7.883871  surprise
5209  13.156899 -10.000698  -1.944780   4.844058   0.378859  surprise
5210  12.455985  -7.318446   3.706867   2.412972  -4.011060  surprise
5211  -6.120132 -11.491291 -14.592528  -7.284732 -10.153592  surprise
5212  -6.127312  -1.714661  -5.814457   1.890175   6.434635  surprise
5213  -4.915219 -13.186498 -14.798534  -7.752739  -9.830679  surprise
5214  11.744241  -8.111529   2.318274   2.226733  -3.432145  surprise
5215  -2.932256  -0.502466  -6.950515  -2.998923   9.315356  surprise
5216  -4.233030   0.399849   4.380675  13.603818  -7.603210  surprise
5217  -9.750824   8.820777   6.617177  -8.320349  -1.680357  surprise
5218  -5.934736   0.816625  -7.321987  -1.818711   9.598814  surprise
5219  -4.119588   0.896150   5.500730  14.009021  -7.732446  surprise
5220  -6.552727 -12.829466 -11.407539  -9.995214 -12.161642  surprise
5221  -5.196412 -11.921412 -17.031633  -8.349002 -12.879315  surprise
5222  13.241105  -6.075448   0.157988   9.225122   0.744396  surprise
5223  15.568847  -1.217556  -3.148701   4.069012   0.099089  surprise
5224  -5.828001   2.757894   5.579908  11.567257  -5.130320  surprise
5225  -5.481954 -12.107015 -17.334603  -6.612293 -10.326990  surprise

In [8]:
#df = df[:2]

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)


from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier(max_depth=2, random_state=0)
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:11: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  # This is added back by InteractiveShellApp.init_path()


In [9]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

cm = confusion_matrix(y_test, y_pred)
print(cm)
print('Accuracy' +str(accuracy_score(y_test, y_pred)))

[[436   1   3]
 [177 123  26]
 [177   1 102]]
Accuracy0.6319311663479924


In [10]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [11]:
from sklearn.decomposition import PCA

pca = PCA()
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)

cm = confusion_matrix(y_test, y_pred)
print(cm)
print('Accuracy' +str(accuracy_score(y_test, y_pred)))

[[436   1   3]
 [177 123  26]
 [177   1 102]]
Accuracy0.6319311663479924


In [12]:
from sklearn.pipeline import Pipeline
from sklearn.decomposition import PCA

finalDf.to_csv (base_path+'/exp-pca-features-smic-renet50.csv', index = False, header=True)
