In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import pandas as pd
import os

base_path = '/content/drive/MyDrive/final-cv-term/samm/resnet50'
csvPath = os.path.sep.join([base_path,
  "{}.csv".format('test-exp-features-resnet50_samm_')])
#csvFile = open(csvPath, "w")

#writer = csv.writer(csvFile)
features_list = ['Label']
features_list.append('Image');
for i in range(1000):
  features_list.append('F' + str(i));

df = pd.read_csv(csvPath,names=features_list)
df = df.dropna(axis=0, how='any', thresh=None, subset=None, inplace=False)

In [3]:
df.head(5)

Label                            Image  ...      F998      F999
0  Anger  Anger_006_006_1_2_006_05578.jpg  ...  2.643626  0.499895
1  Anger  Anger_006_006_1_2_006_05580.jpg  ...  2.803639  0.561227
2  Anger  Anger_006_006_1_2_006_05568.jpg  ...  2.505821  0.803555
3  Anger  Anger_006_006_1_2_006_05598.jpg  ...  3.157849  0.916641
4  Anger  Anger_006_006_1_2_006_05603.jpg  ...  2.840095  1.093602

[5 rows x 1002 columns]

In [4]:
print(features_list)
print('after\n')
features_labels = features_list[2:]
print(features_labels)

['Label', 'Image', 'F0', 'F1', 'F2', 'F3', 'F4', 'F5', 'F6', 'F7', 'F8', 'F9', 'F10', 'F11', 'F12', 'F13', 'F14', 'F15', 'F16', 'F17', 'F18', 'F19', 'F20', 'F21', 'F22', 'F23', 'F24', 'F25', 'F26', 'F27', 'F28', 'F29', 'F30', 'F31', 'F32', 'F33', 'F34', 'F35', 'F36', 'F37', 'F38', 'F39', 'F40', 'F41', 'F42', 'F43', 'F44', 'F45', 'F46', 'F47', 'F48', 'F49', 'F50', 'F51', 'F52', 'F53', 'F54', 'F55', 'F56', 'F57', 'F58', 'F59', 'F60', 'F61', 'F62', 'F63', 'F64', 'F65', 'F66', 'F67', 'F68', 'F69', 'F70', 'F71', 'F72', 'F73', 'F74', 'F75', 'F76', 'F77', 'F78', 'F79', 'F80', 'F81', 'F82', 'F83', 'F84', 'F85', 'F86', 'F87', 'F88', 'F89', 'F90', 'F91', 'F92', 'F93', 'F94', 'F95', 'F96', 'F97', 'F98', 'F99', 'F100', 'F101', 'F102', 'F103', 'F104', 'F105', 'F106', 'F107', 'F108', 'F109', 'F110', 'F111', 'F112', 'F113', 'F114', 'F115', 'F116', 'F117', 'F118', 'F119', 'F120', 'F121', 'F122', 'F123', 'F124', 'F125', 'F126', 'F127', 'F128', 'F129', 'F130', 'F131', 'F132', 'F133', 'F134', 'F135', 'F1

In [ ]:
print(df['Label'])

0           Anger
1           Anger
2           Anger
3           Anger
4           Anger
           ...   
11811    Contempt
11812    Contempt
11813    Contempt
11814    Contempt
11815    Contempt
Name: Label, Length: 11816, dtype: object


In [5]:
from sklearn.preprocessing import StandardScaler

df2 = df[2:]
# Separating out the features
x = df.loc[:, features_labels].values
print(x)
# Separating out the target
y = df.loc[:,['Label']].values
# Standardizing the features
x = StandardScaler().fit_transform(x)


[[ 0.80574965  0.15466988 -1.2785766  ... -3.0401988   2.643626
   0.49989498]
 [ 1.0576025   0.29754388 -1.5853621  ... -3.5736187   2.8036394
   0.56122726]
 [ 0.92266273  0.13254505 -1.2945155  ... -3.6784854   2.505821
   0.8035555 ]
 ...
 [-0.4130261   2.8966475  -2.0379186  ... -3.7967594   0.4173082
  -1.0574834 ]
 [-1.1812334   2.5893993  -1.7979307  ... -3.8555255   0.01933992
  -0.48280343]
 [-0.12696308  3.111554   -3.5209718  ... -4.7129426  -0.49985778
  -0.3029794 ]]


In [6]:
from sklearn.decomposition import PCA
import numpy as np
pca = PCA(n_components=5)
principalComponents = pca.fit_transform(x)
principalDf = pd.DataFrame(data = principalComponents)

principalDf.reset_index(drop=True, inplace=True)
df['Label'].reset_index(drop=True, inplace=True)

finalDf = pd.concat([principalDf, df['Label']], axis=1)

finalDf.tail(20)

0          1         2         3         4     Label
11896 -3.667741  40.670267  6.822533 -3.230453  2.339720  Contempt
11897 -4.022206  39.548056  6.375436 -2.385822  2.295525  Contempt
11898 -3.911305  39.162511  5.953179 -2.865684  2.429238  Contempt
11899 -3.886613  40.134629  5.510792 -2.402632  2.964432  Contempt
11900 -3.773933  38.197537  6.157058 -2.119078  2.469449  Contempt
11901 -4.040149  38.494652  6.319331 -2.716188  2.223812  Contempt
11902 -3.510480  38.871389  5.879921 -2.605206  2.964165  Contempt
11903 -4.042669  38.633489  6.176631 -2.562798  3.799876  Contempt
11904 -3.499343  38.243694  7.069477 -2.255009  2.654260  Contempt
11905 -3.717749  38.736385  5.997555 -1.662576  3.549094  Contempt
11906 -3.871545  38.464794  6.472161 -2.771646  3.368152  Contempt
11907 -3.247066  39.386905  6.873652 -3.365670  2.378815  Contempt
11908 -3.509962  38.155897  6.516649 -2.237526  2.821829  Contempt
11909 -3.457962  40.966951  7.231727 -2.618439  3.426784  Contempt
11910 -3.766702  38.718182  6.419365 -2.358083  2.824404  Contempt
11911 -4.115083  39.366201  6.614669 -2.299365  2.486886  Contempt
11912 -3.657208  39.277172  5.982730 -2.531577  2.813245  Contempt
11913 -3.622504  38.957588  5.669984 -2.308219  3.133500  Contempt
11914 -4.049098  39.124402  6.297235 -2.427675  2.809938  Contempt
11915 -3.268677  39.262846  6.519529 -3.228471  2.698420  Contempt

In [7]:
#df = df[:2]

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)


from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier(max_depth=2, random_state=0)
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:11: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  # This is added back by InteractiveShellApp.init_path()


In [8]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

cm = confusion_matrix(y_test, y_pred)
print(cm)
print('Accuracy' +str(accuracy_score(y_test, y_pred)))

[[790   0   0   0  72   0   0   0]
 [125   0   0   0  40   0   0   0]
 [ 89   0   0   0  40   0   0   0]
 [ 98   0   0   0  14   0   0   0]
 [102   0   0   0 307   0   0   0]
 [298   0   0   0  47  88   0   0]
 [ 79   0   0   0   0   0   0   0]
 [157   0   0   0  38   0   0   0]]
Accuracy0.49706375838926176


In [9]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [10]:
from sklearn.decomposition import PCA

pca = PCA()
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)

cm = confusion_matrix(y_test, y_pred)
print(cm)
print('Accuracy' +str(accuracy_score(y_test, y_pred)))

[[790   0   0   0  72   0   0   0]
 [125   0   0   0  40   0   0   0]
 [ 89   0   0   0  40   0   0   0]
 [ 98   0   0   0  14   0   0   0]
 [102   0   0   0 307   0   0   0]
 [298   0   0   0  47  88   0   0]
 [ 79   0   0   0   0   0   0   0]
 [157   0   0   0  38   0   0   0]]
Accuracy0.49706375838926176


In [11]:
from sklearn.pipeline import Pipeline
from sklearn.decomposition import PCA

finalDf.to_csv (base_path+'/exp-pca-features-samm-renet50.csv', index = False, header=True)
