In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [6]:
import pandas as pd
import os

csvPath = os.path.sep.join(['/content/drive/MyDrive/final-cv-term/casme_square/resnet50',
  "{}.csv".format('exp-features-resnet50-casme-square')])
#csvFile = open(csvPath, "w")

#writer = csv.writer(csvFile)

features_list = ['Label']
features_list.append('Image')
for i in range(1000):
  features_list.append('F' + str(i));

df = pd.read_csv(csvPath,names=features_list)
df = df.dropna(axis=0, how='any', thresh=None, subset=None, inplace=False)

In [7]:
df.head(5)

Label     Image        F0        F1  ...      F996      F997      F998      F999
0  happy  8065.jpg -1.748336  2.556398  ... -0.834176 -0.894336  0.859946  0.565692
1  happy  8498.jpg -3.121665  1.594045  ... -1.366624  0.075278  0.468111  0.635199
2  happy  6122.jpg -2.483034  3.579334  ... -1.899402 -2.697274  0.201750  1.041277
3  happy  7214.jpg -0.727950  2.596000  ... -1.397018 -0.041026 -0.320481  2.543992
4  happy  4417.jpg -1.597735 -1.299836  ... -0.615960 -0.732664 -0.432374  3.304336

[5 rows x 1002 columns]

In [8]:
print(features_list)
print('after\n')
features_labels = features_list[2:]
print(features_labels)

['Label', 'Image', 'F0', 'F1', 'F2', 'F3', 'F4', 'F5', 'F6', 'F7', 'F8', 'F9', 'F10', 'F11', 'F12', 'F13', 'F14', 'F15', 'F16', 'F17', 'F18', 'F19', 'F20', 'F21', 'F22', 'F23', 'F24', 'F25', 'F26', 'F27', 'F28', 'F29', 'F30', 'F31', 'F32', 'F33', 'F34', 'F35', 'F36', 'F37', 'F38', 'F39', 'F40', 'F41', 'F42', 'F43', 'F44', 'F45', 'F46', 'F47', 'F48', 'F49', 'F50', 'F51', 'F52', 'F53', 'F54', 'F55', 'F56', 'F57', 'F58', 'F59', 'F60', 'F61', 'F62', 'F63', 'F64', 'F65', 'F66', 'F67', 'F68', 'F69', 'F70', 'F71', 'F72', 'F73', 'F74', 'F75', 'F76', 'F77', 'F78', 'F79', 'F80', 'F81', 'F82', 'F83', 'F84', 'F85', 'F86', 'F87', 'F88', 'F89', 'F90', 'F91', 'F92', 'F93', 'F94', 'F95', 'F96', 'F97', 'F98', 'F99', 'F100', 'F101', 'F102', 'F103', 'F104', 'F105', 'F106', 'F107', 'F108', 'F109', 'F110', 'F111', 'F112', 'F113', 'F114', 'F115', 'F116', 'F117', 'F118', 'F119', 'F120', 'F121', 'F122', 'F123', 'F124', 'F125', 'F126', 'F127', 'F128', 'F129', 'F130', 'F131', 'F132', 'F133', 'F134', 'F135', 'F1

In [9]:
print(df['Label'])

0       happy
1       happy
2       happy
3       happy
4       happy
        ...  
9569    angry
9570    angry
9571    angry
9572    angry
9573    angry
Name: Label, Length: 9574, dtype: object


In [13]:
from sklearn.preprocessing import StandardScaler

df2 = df[2:]
# Separating out the features
x = df.loc[:, features_labels].values
print(x)
# Separating out the target
y = df.loc[:,['Label']].values
# Standardizing the features
x = StandardScaler().fit_transform(x)


[[-1.7483357   2.556398    0.1151731  ... -0.89433604  0.85994613
   0.5656924 ]
 [-3.1216652   1.5940446  -2.104704   ...  0.07527828  0.46811122
   0.63519907]
 [-2.4830341   3.5793343  -0.58990884 ... -2.6972744   0.20174965
   1.0412769 ]
 ...
 [-0.7224229   1.2907195  -1.5912583  ...  1.5238023   1.1217809
   2.3986778 ]
 [-4.800147    1.12512    -1.3133438  ...  0.19418168  0.04978716
   0.3647853 ]
 [-4.5791044  -0.84558517 -1.5483644  ... -0.209324    0.7197702
   0.669893  ]]


In [14]:
from sklearn.decomposition import PCA
import numpy as np
pca = PCA(n_components=5)
principalComponents = pca.fit_transform(x)
principalDf = pd.DataFrame(data = principalComponents)

principalDf.reset_index(drop=True, inplace=True)
df['Label'].reset_index(drop=True, inplace=True)

finalDf = pd.concat([principalDf, df['Label']], axis=1)

finalDf.tail(20)

0          1          2          3         4  Label
9554 -10.372192   5.540908  20.112967  -3.119895  0.115443  angry
9555  19.585186   3.583306   1.852924  -3.795016  1.208275  angry
9556  -5.849388  20.370450 -14.782753  -5.236090  2.931636  angry
9557  12.775408   4.203394   3.673420   0.014279  5.410415  angry
9558   3.339715  -3.781720  -6.191568   2.694736 -2.675674  angry
9559  22.018136   2.669380   1.862969  -3.832581 -0.106351  angry
9560  -4.509640  19.758692 -13.753280  -5.471034  4.474116  angry
9561  -0.735584  -4.837846  -7.216644   1.470114 -6.100558  angry
9562  -4.485458  -4.777949  -6.084292   7.728122 -6.193224  angry
9563 -10.814892   6.941699  17.447169  -3.139848 -3.090904  angry
9564  -9.578644   7.636507  15.922917  -2.623856 -6.596621  angry
9565  -4.258093  -4.762816  -6.150811  10.328468 -3.807173  angry
9566  -9.853613   5.946025  18.966902  -1.415380 -1.331309  angry
9567  -8.190557   3.577266  13.218970  -0.652887 -5.093878  angry
9568  25.071974   2.099292   4.014499  -4.374938 -0.860625  angry
9569  -9.108460   5.878393  18.711947  -2.333561 -1.530843  angry
9570  27.139279   1.442659   3.972220  -3.234683 -4.593003  angry
9571  -3.574478  -4.495244   5.993579   8.406072  2.706247  angry
9572  14.027939   2.496780  -0.032385   3.587923  2.845907  angry
9573  13.832046   5.324470  -0.557757   4.013542  3.163459  angry

In [16]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x, y.ravel(), test_size=0.2, random_state=0)


from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier(max_depth=2, random_state=0)
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

In [17]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

cm = confusion_matrix(y_test, y_pred)
print(cm)
print('Accuracy' +str(accuracy_score(y_test, y_pred)))

[[  0   0   6   0 316   0   0   0]
 [  0   0   0   0  15   0   0   0]
 [  0   0  36   0 373   0   0   0]
 [  0   0   0   0 115   0   0   0]
 [  0   0   1   0 862   0   0   0]
 [  0   0   0   0  56   0   0   0]
 [  0   0   0   0  30   0   0   0]
 [  0   0  22   0  83   0   0   0]]
Accuracy0.4689295039164491


In [18]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [19]:
from sklearn.decomposition import PCA

pca = PCA()
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)

cm = confusion_matrix(y_test, y_pred)
print(cm)
print('Accuracy' +str(accuracy_score(y_test, y_pred)))

[[  0   0   6   0 316   0   0   0]
 [  0   0   0   0  15   0   0   0]
 [  0   0  36   0 373   0   0   0]
 [  0   0   0   0 115   0   0   0]
 [  0   0   1   0 862   0   0   0]
 [  0   0   0   0  56   0   0   0]
 [  0   0   0   0  30   0   0   0]
 [  0   0  22   0  83   0   0   0]]
Accuracy0.4689295039164491


In [20]:
from sklearn.pipeline import Pipeline
from sklearn.decomposition import PCA

finalDf.to_csv ('/content/drive/MyDrive/final-cv-term/casme_square/resnet50/exp-pca-features-casme-square-resnet50.csv', index = False, header=True)
