In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import pandas as pd
import os

base_path = '/content/drive/MyDrive/final-cv-term/SMIC/densenet'
csvPath = os.path.sep.join([base_path,
  "{}.csv".format('SMIC')])
#csvFile = open(csvPath, "w")

#writer = csv.writer(csvFile)
features_list = ['Label']
features_list.append('Image');
for i in range(1000):
  features_list.append('F' + str(i));

df = pd.read_csv(csvPath,names=features_list)
df = df.dropna(axis=0, how='any', thresh=None, subset=None, inplace=False)

In [3]:
df.head(5)

Label     Image        F0  ...      F997      F998      F999
0  positive  2574.jpg  6.659350  ...  7.111677 -4.517623 -4.427988
1  positive  2682.jpg  2.082709  ...  1.741773 -2.576770 -6.013964
2  positive  2582.jpg  6.621839  ...  7.498795 -4.088332 -4.865753
3  positive  3469.jpg  6.650172  ...  9.374807  3.514114  1.259806
4  positive  3659.jpg  2.434278  ...  2.286302 -3.495021 -8.371401

[5 rows x 1002 columns]

In [4]:
print(features_list)
print('after\n')
features_labels = features_list[2:]
print(features_labels)

['Label', 'Image', 'F0', 'F1', 'F2', 'F3', 'F4', 'F5', 'F6', 'F7', 'F8', 'F9', 'F10', 'F11', 'F12', 'F13', 'F14', 'F15', 'F16', 'F17', 'F18', 'F19', 'F20', 'F21', 'F22', 'F23', 'F24', 'F25', 'F26', 'F27', 'F28', 'F29', 'F30', 'F31', 'F32', 'F33', 'F34', 'F35', 'F36', 'F37', 'F38', 'F39', 'F40', 'F41', 'F42', 'F43', 'F44', 'F45', 'F46', 'F47', 'F48', 'F49', 'F50', 'F51', 'F52', 'F53', 'F54', 'F55', 'F56', 'F57', 'F58', 'F59', 'F60', 'F61', 'F62', 'F63', 'F64', 'F65', 'F66', 'F67', 'F68', 'F69', 'F70', 'F71', 'F72', 'F73', 'F74', 'F75', 'F76', 'F77', 'F78', 'F79', 'F80', 'F81', 'F82', 'F83', 'F84', 'F85', 'F86', 'F87', 'F88', 'F89', 'F90', 'F91', 'F92', 'F93', 'F94', 'F95', 'F96', 'F97', 'F98', 'F99', 'F100', 'F101', 'F102', 'F103', 'F104', 'F105', 'F106', 'F107', 'F108', 'F109', 'F110', 'F111', 'F112', 'F113', 'F114', 'F115', 'F116', 'F117', 'F118', 'F119', 'F120', 'F121', 'F122', 'F123', 'F124', 'F125', 'F126', 'F127', 'F128', 'F129', 'F130', 'F131', 'F132', 'F133', 'F134', 'F135', 'F1

In [5]:
print(df['Label'])

0       positive
1       positive
2       positive
3       positive
4       positive
          ...   
5221    surprise
5222    surprise
5223    surprise
5224    surprise
5225    surprise
Name: Label, Length: 5226, dtype: object


In [6]:
from sklearn.preprocessing import StandardScaler

df2 = df[2:]
# Separating out the features
x = df.loc[:, features_labels].values
print(x)
# Separating out the target
y = df.loc[:,['Label']].values
# Standardizing the features
x = StandardScaler().fit_transform(x)


[[  6.6593504  -10.733257     4.052586   ...   7.1116767   -4.517623
   -4.427988  ]
 [  2.0827088   -6.4376817    5.6045127  ...   1.7417729   -2.5767703
   -6.013964  ]
 [  6.621839   -10.382027     5.08657    ...   7.498795    -4.088332
   -4.8657527 ]
 ...
 [  1.8723981   -5.8806458    7.215945   ...   4.7153816   -5.1179056
   -2.1014442 ]
 [  2.6260636  -10.64071      1.5219221  ...   3.1239386   -0.70273364
   -4.1218367 ]
 [  5.4776697   -7.50208      3.8127518  ...   6.9937363   -6.4156427
   -5.1586094 ]]


In [7]:
from sklearn.decomposition import PCA
import numpy as np
pca = PCA(n_components=5)
principalComponents = pca.fit_transform(x)
principalDf = pd.DataFrame(data = principalComponents)

principalDf.reset_index(drop=True, inplace=True)
df['Label'].reset_index(drop=True, inplace=True)

finalDf = pd.concat([principalDf, df['Label']], axis=1)

finalDf.tail(20)

0          1          2          3          4     Label
5206   8.423070  -1.655728   2.647269   3.412287  -4.055447  surprise
5207   7.462617   7.299182  11.486063 -12.626919  18.862452  surprise
5208   8.302713  -1.047609   1.398256   3.889035  -5.051797  surprise
5209  17.714911  19.037886  -1.451854   5.951954   1.825267  surprise
5210  -0.017093   8.945182  -3.287901   1.073911  -8.177385  surprise
5211   7.946985  -8.081522  21.054945   0.664455  -8.484106  surprise
5212   1.049667  -1.590997   9.805375   8.803815  -2.195729  surprise
5213   7.514535  -7.788597  20.715049  -0.420409  -7.606645  surprise
5214  -0.632896   9.153202  -4.448506   1.741327  -8.608042  surprise
5215   9.644045  -1.042130   3.025236   4.355338  -4.266940  surprise
5216 -12.497011  -4.780583 -10.001897  -9.055171   1.371957  surprise
5217  -9.614248  -2.665781   1.542284  10.506059  -4.871395  surprise
5218  -4.943682  -1.709412   8.614871   9.238509  -2.101784  surprise
5219 -13.277255  -5.812429 -10.411492  -9.183891   2.124481  surprise
5220   3.532480  -9.786461  22.449611   0.396552 -10.935539  surprise
5221   5.894511  -8.748347  24.670666   0.463290 -11.333905  surprise
5222  18.397387  19.824542  -1.291464   5.460875   3.980171  surprise
5223  19.419788  -6.193003 -11.345982  -6.852611  -6.295395  surprise
5224 -12.282851 -10.255044 -11.262822  -5.010600  -0.393505  surprise
5225  10.394299  -7.546461  21.440097  -0.700228  -9.129453  surprise

In [8]:
#df = df[:2]

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)


from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier(max_depth=2, random_state=0)
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:11: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  # This is added back by InteractiveShellApp.init_path()


In [9]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

cm = confusion_matrix(y_test, y_pred)
print(cm)
print('Accuracy' +str(accuracy_score(y_test, y_pred)))

[[398   0  42]
 [164 134  28]
 [139   0 141]]
Accuracy0.6434034416826003


In [10]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [12]:
from sklearn.decomposition import PCA

pca = PCA()
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)

cm = confusion_matrix(y_test, y_pred)
print(cm)
print('Accuracy' +str(accuracy_score(y_test, y_pred)))

[[398   0  42]
 [164 134  28]
 [139   0 141]]
Accuracy0.6434034416826003


In [13]:
from sklearn.pipeline import Pipeline
from sklearn.decomposition import PCA

finalDf.to_csv (base_path+'/exp-pca-features-smic-densnet.csv', index = False, header=True)
