In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import pandas as pd
import os

base_path = '/content/drive/MyDrive/final-cv-term/casm11/vgg16'
csvPath = os.path.sep.join([base_path,
  "{}.csv".format('exp-features-vgg16-casmeII_update')])
#csvFile = open(csvPath, "w")

#writer = csv.writer(csvFile)
features_list = ['Label']
features_list.append('Image');
for i in range(1000):
  features_list.append('F' + str(i));

df = pd.read_csv(csvPath,names=features_list)
df = df.dropna(axis=0, how='any', thresh=None, subset=None, inplace=False)

In [3]:
df.head(5)

Label                                Image  ...       F998      F999
0  happiness  happiness_01_EP02_01f_reg_img65.jpg  ...  16.970280 -0.617168
1  happiness  happiness_01_EP02_01f_reg_img59.jpg  ...  20.236687 -4.353861
2  happiness  happiness_01_EP02_01f_reg_img47.jpg  ...  17.546242 -2.577536
3  happiness  happiness_01_EP02_01f_reg_img57.jpg  ...  18.850073 -4.661343
4  happiness  happiness_01_EP02_01f_reg_img64.jpg  ...  18.108582 -1.790572

[5 rows x 1002 columns]

In [4]:
print(features_list)
print('after\n')
features_labels = features_list[2:]
print(features_labels)

['Label', 'Image', 'F0', 'F1', 'F2', 'F3', 'F4', 'F5', 'F6', 'F7', 'F8', 'F9', 'F10', 'F11', 'F12', 'F13', 'F14', 'F15', 'F16', 'F17', 'F18', 'F19', 'F20', 'F21', 'F22', 'F23', 'F24', 'F25', 'F26', 'F27', 'F28', 'F29', 'F30', 'F31', 'F32', 'F33', 'F34', 'F35', 'F36', 'F37', 'F38', 'F39', 'F40', 'F41', 'F42', 'F43', 'F44', 'F45', 'F46', 'F47', 'F48', 'F49', 'F50', 'F51', 'F52', 'F53', 'F54', 'F55', 'F56', 'F57', 'F58', 'F59', 'F60', 'F61', 'F62', 'F63', 'F64', 'F65', 'F66', 'F67', 'F68', 'F69', 'F70', 'F71', 'F72', 'F73', 'F74', 'F75', 'F76', 'F77', 'F78', 'F79', 'F80', 'F81', 'F82', 'F83', 'F84', 'F85', 'F86', 'F87', 'F88', 'F89', 'F90', 'F91', 'F92', 'F93', 'F94', 'F95', 'F96', 'F97', 'F98', 'F99', 'F100', 'F101', 'F102', 'F103', 'F104', 'F105', 'F106', 'F107', 'F108', 'F109', 'F110', 'F111', 'F112', 'F113', 'F114', 'F115', 'F116', 'F117', 'F118', 'F119', 'F120', 'F121', 'F122', 'F123', 'F124', 'F125', 'F126', 'F127', 'F128', 'F129', 'F130', 'F131', 'F132', 'F133', 'F134', 'F135', 'F1

In [5]:
print(df['Label'])

0        happiness
1        happiness
2        happiness
3        happiness
4        happiness
           ...    
17119      sadness
17120      sadness
17121      sadness
17122      sadness
17123      sadness
Name: Label, Length: 17124, dtype: object


In [6]:
from sklearn.preprocessing import StandardScaler

df2 = df[2:]
# Separating out the features
x = df.loc[:, features_labels].values
print(x)
# Separating out the target
y = df.loc[:,['Label']].values
# Standardizing the features
x = StandardScaler().fit_transform(x)


[[ -5.9438      -3.2595615   -9.481815   ...  -0.8013971   16.97028
   -0.61716795]
 [ -5.0463915   -2.0285325   -9.744723   ...   1.2344835   20.236687
   -4.3538613 ]
 [ -4.81546     -2.7478218   -9.281      ...  -0.71625507  17.546242
   -2.577536  ]
 ...
 [-10.348087    -4.524208    -9.150717   ...   4.4509964   12.746233
   -1.157495  ]
 [ -9.825083    -0.43907356  -8.03075    ...   5.464645    13.490485
   -2.7152727 ]
 [-11.360577     1.4403219  -10.074522   ...   3.5482328   15.692754
   -2.1216788 ]]


In [7]:
from sklearn.decomposition import PCA
import numpy as np
pca = PCA(n_components=5)
principalComponents = pca.fit_transform(x)
principalDf = pd.DataFrame(data = principalComponents)

principalDf.reset_index(drop=True, inplace=True)
df['Label'].reset_index(drop=True, inplace=True)

finalDf = pd.concat([principalDf, df['Label']], axis=1)

finalDf.tail(20)

0         1          2         3         4    Label
17104 -1.653089  3.100179  19.564169  8.054358  2.276233  sadness
17105 -2.139995  3.970137  19.233366  7.639315  2.159903  sadness
17106 -1.718161  4.053834  19.226198  7.304005  2.811217  sadness
17107 -2.489723  2.506022  18.249349  8.652160  0.660485  sadness
17108 -1.847562  2.505147  18.038748  8.493929  0.327273  sadness
17109 -2.384271  2.441439  18.965772  8.295985  0.176777  sadness
17110 -2.098171  4.587079  19.918682  6.257556  1.428848  sadness
17111 -2.340017  2.952249  19.717281  6.981274  1.389106  sadness
17112 -2.204014  2.923126  18.714902  7.986096  0.862892  sadness
17113 -1.890346  1.894545  18.804608  8.940764  0.279050  sadness
17114 -2.483424  3.963685  20.108377  8.426552  1.719618  sadness
17115 -1.649778  2.512284  19.670625  7.782117  0.417660  sadness
17116 -2.512356  3.847943  19.200881  6.481382  1.051959  sadness
17117 -2.004425  4.501558  19.116254  7.465546  1.738175  sadness
17118 -2.118291  4.305902  19.941985  7.543337  2.015973  sadness
17119 -1.625759  4.276398  19.389272  6.889400  3.181733  sadness
17120 -2.190031  3.136973  18.898450  8.140014  0.500742  sadness
17121 -1.571915  2.533572  18.532844  8.565087  0.250713  sadness
17122 -2.103854  4.397292  20.585860  6.755790  1.542150  sadness
17123 -2.072142  5.197351  21.631732  6.924574  2.975382  sadness

In [8]:
#df = df[:2]

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)


from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier(max_depth=2, random_state=0)
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:11: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  # This is added back by InteractiveShellApp.init_path()


In [9]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

cm = confusion_matrix(y_test, y_pred)
print(cm)
print('Accuracy' +str(accuracy_score(y_test, y_pred)))

[[ 337    0    0  512    0    0    0]
 [   0    0    0   19    0    0    0]
 [  81    0    0  396    0    0    0]
 [  33    0    0 1225    0    0    0]
 [ 104    0    0  343    0    0    0]
 [  22    0    0   12    0    0    0]
 [  25    0    0  316    0    0    0]]
Accuracy0.45605839416058397


In [10]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [11]:
from sklearn.decomposition import PCA

pca = PCA()
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)

cm = confusion_matrix(y_test, y_pred)
print(cm)
print('Accuracy' +str(accuracy_score(y_test, y_pred)))

[[ 337    0    0  512    0    0    0]
 [   0    0    0   19    0    0    0]
 [  81    0    0  396    0    0    0]
 [  33    0    0 1225    0    0    0]
 [ 104    0    0  343    0    0    0]
 [  22    0    0   12    0    0    0]
 [  25    0    0  316    0    0    0]]
Accuracy0.45605839416058397


In [12]:
from sklearn.pipeline import Pipeline
from sklearn.decomposition import PCA

finalDf.to_csv (base_path+'/exp-pca-features-casmeII-vgg16_update.csv', index = False, header=True)
