In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
import pandas as pd
import os

base_path = '/content/drive/MyDrive/final-cv-term/SMIC/vgg16/'
csvPath = os.path.sep.join([base_path,
  "{}.csv".format('test-exp-features-vgg16_smic_')])
#csvFile = open(csvPath, "w")

#writer = csv.writer(csvFile)
features_list = ['Label']
features_list.append('Image');
for i in range(1000):
  features_list.append('F' + str(i));

df = pd.read_csv(csvPath,names=features_list)
df = df.dropna(axis=0, how='any', thresh=None, subset=None, inplace=False)

In [ ]:
df.head(5)

Label                            Image  ...      F998      F999
0  Anger  Anger_006_006_1_2_006_05578.jpg  ...  4.645138  2.474633
1  Anger  Anger_006_006_1_2_006_05580.jpg  ...  4.465715  2.272745
2  Anger  Anger_006_006_1_2_006_05568.jpg  ...  3.543747  2.230488
3  Anger  Anger_006_006_1_2_006_05598.jpg  ...  4.259086  2.288517
4  Anger  Anger_006_006_1_2_006_05603.jpg  ...  4.559295  2.663526

[5 rows x 1002 columns]

In [4]:
print(features_list)
print('after\n')
features_labels = features_list[2:]
print(features_labels)

['Label', 'Image', 'F0', 'F1', 'F2', 'F3', 'F4', 'F5', 'F6', 'F7', 'F8', 'F9', 'F10', 'F11', 'F12', 'F13', 'F14', 'F15', 'F16', 'F17', 'F18', 'F19', 'F20', 'F21', 'F22', 'F23', 'F24', 'F25', 'F26', 'F27', 'F28', 'F29', 'F30', 'F31', 'F32', 'F33', 'F34', 'F35', 'F36', 'F37', 'F38', 'F39', 'F40', 'F41', 'F42', 'F43', 'F44', 'F45', 'F46', 'F47', 'F48', 'F49', 'F50', 'F51', 'F52', 'F53', 'F54', 'F55', 'F56', 'F57', 'F58', 'F59', 'F60', 'F61', 'F62', 'F63', 'F64', 'F65', 'F66', 'F67', 'F68', 'F69', 'F70', 'F71', 'F72', 'F73', 'F74', 'F75', 'F76', 'F77', 'F78', 'F79', 'F80', 'F81', 'F82', 'F83', 'F84', 'F85', 'F86', 'F87', 'F88', 'F89', 'F90', 'F91', 'F92', 'F93', 'F94', 'F95', 'F96', 'F97', 'F98', 'F99', 'F100', 'F101', 'F102', 'F103', 'F104', 'F105', 'F106', 'F107', 'F108', 'F109', 'F110', 'F111', 'F112', 'F113', 'F114', 'F115', 'F116', 'F117', 'F118', 'F119', 'F120', 'F121', 'F122', 'F123', 'F124', 'F125', 'F126', 'F127', 'F128', 'F129', 'F130', 'F131', 'F132', 'F133', 'F134', 'F135', 'F1

In [5]:
print(df['Label'])

0       positive
1       positive
2       positive
3       positive
4       positive
          ...   
5221    surprise
5222    surprise
5223    surprise
5224    surprise
5225    surprise
Name: Label, Length: 5226, dtype: object


In [6]:
from sklearn.preprocessing import StandardScaler

df2 = df[2:]
# Separating out the features
x = df.loc[:, features_labels].values
print(x)
# Separating out the target
y = df.loc[:,['Label']].values
# Standardizing the features
x = StandardScaler().fit_transform(x)


[[ 0.10098869 -0.20692897 18.788399   ...  1.5861819   2.3520718
  -1.0806127 ]
 [ 1.0248652   1.202286    4.3941107  ... -0.30497944 -3.9072719
  -0.6128814 ]
 [-7.9152994   1.4192355  18.407192   ...  0.8400147   4.514324
   0.20081973]
 ...
 [-0.5843551   0.6995121   0.9868188  ... -2.3271272  11.661831
  -0.97575915]
 [-3.4960954   0.40498757  8.286175   ...  3.477501   -9.299269
   1.1207538 ]
 [ 0.34689593 -6.097021    8.560209   ... -3.2782602   0.8322656
  -1.7643142 ]]


In [7]:
from sklearn.decomposition import PCA
import numpy as np
pca = PCA(n_components=5)
principalComponents = pca.fit_transform(x)
principalDf = pd.DataFrame(data = principalComponents)

principalDf.reset_index(drop=True, inplace=True)
df['Label'].reset_index(drop=True, inplace=True)

finalDf = pd.concat([principalDf, df['Label']], axis=1)

finalDf.tail(20)

0         1          2          3          4     Label
5206  -2.365204 -2.787504   1.499805   4.527187   1.997042  surprise
5207  -5.655295 -3.140429 -10.553613  12.083085  -4.215424  surprise
5208  -2.736204 -2.882738   2.950645   3.858000   2.347501  surprise
5209  12.641988 -0.241214  -2.601180  10.541322  13.920444  surprise
5210  10.031106 -4.818417  -3.755247   2.849833   0.641111  surprise
5211  -8.215087  5.813348   1.598433  17.592669 -14.259874  surprise
5212  -4.778015 -1.374868   2.852950   5.893799   4.673647  surprise
5213  -7.692184  5.796041   1.962165  18.833395 -14.533308  surprise
5214  11.026475 -4.445438  -3.414592   1.973827   0.908140  surprise
5215  -1.960031 -3.340231   2.498563   4.348125   2.581964  surprise
5216  -3.951790 -3.631785 -14.581257 -13.708214  -5.107817  surprise
5217  -9.117920  1.659687   9.473266  -6.567953   1.805437  surprise
5218  -5.403631 -0.185195   3.544504   7.986896   1.512498  surprise
5219  -4.794888 -3.063980 -13.850009 -12.615438  -4.303888  surprise
5220  -7.236974  7.385944   4.339797  12.582464 -15.391000  surprise
5221  -8.987576  4.307230   1.713311  16.246430 -15.154743  surprise
5222  13.139567 -3.313055  -3.473707   7.722179  17.460875  surprise
5223   7.825186 -7.355475  -1.998495   0.139768   7.789854  surprise
5224  -6.079384 -2.749494 -11.507681 -11.751430  -3.740792  surprise
5225  -9.308091  3.621348   0.923461  17.367621 -15.582870  surprise

In [8]:
#df = df[:2]

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)


from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier(max_depth=2, random_state=0)
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:11: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  # This is added back by InteractiveShellApp.init_path()


In [9]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

cm = confusion_matrix(y_test, y_pred)
print(cm)
print('Accuracy' +str(accuracy_score(y_test, y_pred)))

[[430  10   0]
 [164 150  12]
 [176  14  90]]
Accuracy0.6405353728489483


In [10]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [11]:
from sklearn.decomposition import PCA

pca = PCA()
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)

cm = confusion_matrix(y_test, y_pred)
print(cm)
print('Accuracy' +str(accuracy_score(y_test, y_pred)))

[[430  10   0]
 [164 150  12]
 [176  14  90]]
Accuracy0.6405353728489483


In [12]:
from sklearn.pipeline import Pipeline
from sklearn.decomposition import PCA

finalDf.to_csv (base_path+'/exp-pca-features-smic-vgg16.csv', index = False, header=True)
