In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import pandas as pd
import os

base_path = '/content/drive/MyDrive/final-cv-term/samm/vgg16'
csvPath = os.path.sep.join([base_path,
  "{}.csv".format('test-exp-features-vgg16_samm_')])
#csvFile = open(csvPath, "w")

#writer = csv.writer(csvFile)
features_list = ['Label']
features_list.append('Image');
for i in range(1000):
  features_list.append('F' + str(i));

df = pd.read_csv(csvPath,names=features_list)
df = df.dropna(axis=0, how='any', thresh=None, subset=None, inplace=False)

In [3]:
df.head(5)

Label                            Image  ...      F998      F999
0  Anger  Anger_006_006_1_2_006_05578.jpg  ...  4.645138  2.474633
1  Anger  Anger_006_006_1_2_006_05580.jpg  ...  4.465715  2.272745
2  Anger  Anger_006_006_1_2_006_05568.jpg  ...  3.543747  2.230488
3  Anger  Anger_006_006_1_2_006_05598.jpg  ...  4.259086  2.288517
4  Anger  Anger_006_006_1_2_006_05603.jpg  ...  4.559295  2.663526

[5 rows x 1002 columns]

In [4]:
print(features_list)
print('after\n')
features_labels = features_list[2:]
print(features_labels)

['Label', 'Image', 'F0', 'F1', 'F2', 'F3', 'F4', 'F5', 'F6', 'F7', 'F8', 'F9', 'F10', 'F11', 'F12', 'F13', 'F14', 'F15', 'F16', 'F17', 'F18', 'F19', 'F20', 'F21', 'F22', 'F23', 'F24', 'F25', 'F26', 'F27', 'F28', 'F29', 'F30', 'F31', 'F32', 'F33', 'F34', 'F35', 'F36', 'F37', 'F38', 'F39', 'F40', 'F41', 'F42', 'F43', 'F44', 'F45', 'F46', 'F47', 'F48', 'F49', 'F50', 'F51', 'F52', 'F53', 'F54', 'F55', 'F56', 'F57', 'F58', 'F59', 'F60', 'F61', 'F62', 'F63', 'F64', 'F65', 'F66', 'F67', 'F68', 'F69', 'F70', 'F71', 'F72', 'F73', 'F74', 'F75', 'F76', 'F77', 'F78', 'F79', 'F80', 'F81', 'F82', 'F83', 'F84', 'F85', 'F86', 'F87', 'F88', 'F89', 'F90', 'F91', 'F92', 'F93', 'F94', 'F95', 'F96', 'F97', 'F98', 'F99', 'F100', 'F101', 'F102', 'F103', 'F104', 'F105', 'F106', 'F107', 'F108', 'F109', 'F110', 'F111', 'F112', 'F113', 'F114', 'F115', 'F116', 'F117', 'F118', 'F119', 'F120', 'F121', 'F122', 'F123', 'F124', 'F125', 'F126', 'F127', 'F128', 'F129', 'F130', 'F131', 'F132', 'F133', 'F134', 'F135', 'F1

In [5]:
print(df['Label'])

0           Anger
1           Anger
2           Anger
3           Anger
4           Anger
           ...   
11811    Contempt
11812    Contempt
11813    Contempt
11814    Contempt
11815    Contempt
Name: Label, Length: 11816, dtype: object


In [6]:
from sklearn.preprocessing import StandardScaler

df2 = df[2:]
# Separating out the features
x = df.loc[:, features_labels].values
print(x)
# Separating out the target
y = df.loc[:,['Label']].values
# Standardizing the features
x = StandardScaler().fit_transform(x)


[[  3.1252618    5.452333    -9.526454   ...  -0.5894575    4.645138
    2.4746332 ]
 [  2.358038     3.976314   -10.405916   ...   0.5143151    4.465715
    2.2727451 ]
 [  2.3003864    5.839467   -10.2030325  ...   0.33038902   3.5437474
    2.2304883 ]
 ...
 [  7.0118647   14.6770115    1.8806     ...   3.598857    19.634499
   -2.1226406 ]
 [  4.445105    14.268923     3.5602064  ...   3.464839    17.24492
   -7.482588  ]
 [  6.8515577   15.282919     0.33404446 ...   6.0485396   16.707699
   -5.2631583 ]]


In [7]:
from sklearn.decomposition import PCA
import numpy as np
pca = PCA(n_components=5)
principalComponents = pca.fit_transform(x)
principalDf = pd.DataFrame(data = principalComponents)

principalDf.reset_index(drop=True, inplace=True)
df['Label'].reset_index(drop=True, inplace=True)

finalDf = pd.concat([principalDf, df['Label']], axis=1)

finalDf.tail(20)

0          1         2         3         4     Label
11796 -11.635227  39.840998  1.060652 -6.154814 -0.248391  Contempt
11797 -11.606654  39.749869  1.485559 -5.752165 -0.334475  Contempt
11798 -12.060815  39.533109  1.341502 -5.694463 -0.039644  Contempt
11799 -12.355818  40.288436  1.735374 -5.649254  0.361668  Contempt
11800 -11.625071  39.428513  2.035821 -6.244714  0.985489  Contempt
11801 -11.995198  40.033267  1.581935 -5.569428  0.031297  Contempt
11802 -11.754933  38.592113  1.540654 -5.796565 -0.103231  Contempt
11803 -12.927065  40.560227  2.544346 -5.845086 -0.086856  Contempt
11804 -11.543007  39.574454  1.648684 -5.995362  0.813802  Contempt
11805 -12.413053  40.198629  2.022600 -5.939585  0.176328  Contempt
11806 -12.329152  39.731605  1.957977 -5.582673  0.521078  Contempt
11807 -11.366562  39.661241  1.791606 -5.983214 -0.235262  Contempt
11808 -11.994010  39.949382  1.832445 -6.271843  0.274711  Contempt
11809 -11.691239  40.041032  0.895277 -6.109015 -0.048079  Contempt
11810 -11.592098  39.591864  1.810804 -6.244471  0.557261  Contempt
11811 -12.549342  40.332016  2.172567 -6.029741  0.282420  Contempt
11812 -12.229474  40.634632  1.670992 -6.219107  0.077797  Contempt
11813 -12.553897  39.728206  2.296185 -5.781947  0.155400  Contempt
11814 -11.840227  39.542907  1.781021 -5.769406  0.999823  Contempt
11815 -11.325068  39.606681  1.200939 -5.940179  0.009735  Contempt

In [8]:
#df = df[:2]

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)


from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier(max_depth=2, random_state=0)
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:11: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  # This is added back by InteractiveShellApp.init_path()


In [9]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

cm = confusion_matrix(y_test, y_pred)
print(cm)
print('Accuracy' +str(accuracy_score(y_test, y_pred)))

[[790   0   0   0  40   9   0   0]
 [ 94   0   0   0  39  33   0   0]
 [ 70   0   0   0  58   7   0   0]
 [ 85   0   0   0  13   0   0   0]
 [ 58   0   0   0 316  37   0   0]
 [178   0   0   0  60 200   0   0]
 [ 85   0   0   0   0   0   0   0]
 [151   0   0   0  38   3   0   0]]
Accuracy0.5524534686971235


In [10]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [11]:
from sklearn.decomposition import PCA

pca = PCA()
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)

cm = confusion_matrix(y_test, y_pred)
print(cm)
print('Accuracy' +str(accuracy_score(y_test, y_pred)))

[[790   0   0   0  40   9   0   0]
 [ 94   0   0   0  39  33   0   0]
 [ 70   0   0   0  58   7   0   0]
 [ 85   0   0   0  13   0   0   0]
 [ 58   0   0   0 316  37   0   0]
 [178   0   0   0  60 200   0   0]
 [ 85   0   0   0   0   0   0   0]
 [151   0   0   0  38   3   0   0]]
Accuracy0.5524534686971235


In [12]:
from sklearn.pipeline import Pipeline
from sklearn.decomposition import PCA

finalDf.to_csv (base_path+'/exp-pca-features-samm-vgg16.csv', index = False, header=True)
