In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import pandas as pd
import os

base_path = '/content/drive/MyDrive/final-cv-term/casme_square/vgg16'
csvPath = os.path.sep.join([base_path,
  "{}.csv".format('exp-features-vgg16-casme-square')])
#csvFile = open(csvPath, "w")

#writer = csv.writer(csvFile)
features_list = ['Label']
features_list.append('Image');
for i in range(1000):
  features_list.append('F' + str(i));

df = pd.read_csv(csvPath,names=features_list)
df = df.dropna(axis=0, how='any', thresh=None, subset=None, inplace=False)

In [3]:
df.head(5)

Label     Image        F0        F1  ...      F996      F997       F998      F999
0  happy  8065.jpg -4.195277 -3.470712  ... -7.033585  2.532160  -1.014029  9.760128
1  happy  8498.jpg  1.742481 -6.092420  ... -6.780611  4.225898   7.943995  0.639833
2  happy  6122.jpg -0.410126 -5.470053  ...  0.363483  0.302264   3.123448  8.826413
3  happy  7214.jpg -3.371110  6.811910  ...  1.442258 -9.714754  12.245172 -3.371884
4  happy  4417.jpg  4.328157 -0.469196  ... -2.538194  5.592649  -0.688487  4.822467

[5 rows x 1002 columns]

In [4]:
print(features_list)
print('after\n')
features_labels = features_list[2:]
print(features_labels)

['Label', 'Image', 'F0', 'F1', 'F2', 'F3', 'F4', 'F5', 'F6', 'F7', 'F8', 'F9', 'F10', 'F11', 'F12', 'F13', 'F14', 'F15', 'F16', 'F17', 'F18', 'F19', 'F20', 'F21', 'F22', 'F23', 'F24', 'F25', 'F26', 'F27', 'F28', 'F29', 'F30', 'F31', 'F32', 'F33', 'F34', 'F35', 'F36', 'F37', 'F38', 'F39', 'F40', 'F41', 'F42', 'F43', 'F44', 'F45', 'F46', 'F47', 'F48', 'F49', 'F50', 'F51', 'F52', 'F53', 'F54', 'F55', 'F56', 'F57', 'F58', 'F59', 'F60', 'F61', 'F62', 'F63', 'F64', 'F65', 'F66', 'F67', 'F68', 'F69', 'F70', 'F71', 'F72', 'F73', 'F74', 'F75', 'F76', 'F77', 'F78', 'F79', 'F80', 'F81', 'F82', 'F83', 'F84', 'F85', 'F86', 'F87', 'F88', 'F89', 'F90', 'F91', 'F92', 'F93', 'F94', 'F95', 'F96', 'F97', 'F98', 'F99', 'F100', 'F101', 'F102', 'F103', 'F104', 'F105', 'F106', 'F107', 'F108', 'F109', 'F110', 'F111', 'F112', 'F113', 'F114', 'F115', 'F116', 'F117', 'F118', 'F119', 'F120', 'F121', 'F122', 'F123', 'F124', 'F125', 'F126', 'F127', 'F128', 'F129', 'F130', 'F131', 'F132', 'F133', 'F134', 'F135', 'F1

In [5]:
print(df['Label'])

0       happy
1       happy
2       happy
3       happy
4       happy
        ...  
9569    angry
9570    angry
9571    angry
9572    angry
9573    angry
Name: Label, Length: 9574, dtype: object


In [6]:
from sklearn.preprocessing import StandardScaler

df2 = df[2:]
# Separating out the features
x = df.loc[:, features_labels].values
print(x)
# Separating out the target
y = df.loc[:,['Label']].values
# Standardizing the features
x = StandardScaler().fit_transform(x)


[[-4.1952767 -3.4707117  5.6351943 ...  2.5321605 -1.014029   9.760128 ]
 [ 1.7424815 -6.0924196  6.3953557 ...  4.225898   7.943995   0.6398332]
 [-0.4101255 -5.4700527  8.231068  ...  0.3022641  3.1234484  8.826413 ]
 ...
 [-4.327016  -1.7132416 19.998272  ...  4.8265753  5.0667257 -3.0017827]
 [ 2.664036  -2.9588752 -4.6668196 ...  7.842613   3.2596703 -1.9765801]
 [ 3.2873902 -5.8287497  0.3892787 ...  5.3944874  3.9296734 -5.3071465]]


In [7]:
from sklearn.decomposition import PCA
import numpy as np
pca = PCA(n_components=5)
principalComponents = pca.fit_transform(x)
principalDf = pd.DataFrame(data = principalComponents)

principalDf.reset_index(drop=True, inplace=True)
df['Label'].reset_index(drop=True, inplace=True)

finalDf = pd.concat([principalDf, df['Label']], axis=1)

finalDf.tail(20)

0          1          2          3         4  Label
9554  30.749459  -3.359808  -5.479249   1.888088 -1.605250  angry
9555  -9.651115 -10.194643 -13.026077  -2.464878 -1.390713  angry
9556  -5.490297  21.568373  -8.988325   0.525726  1.809425  angry
9557  -6.705230  -8.324135 -10.624511  -0.981631 -1.647234  angry
9558  -6.225038   0.974684   3.300208   0.193728 -4.442310  angry
9559  -9.384692 -11.131083 -13.682607  -3.475846 -1.566070  angry
9560  -6.531507  20.392835  -7.835934  -2.435973  1.639341  angry
9561  -3.010777   2.995065   3.869012  -1.833549 -6.225147  angry
9562  -3.568597   3.364144   3.856696   6.306284 -2.139961  angry
9563  24.071593  -1.794978  -3.496346   3.239367 -3.604399  angry
9564  24.263826   1.484778  -4.904270  -0.793982 -3.758044  angry
9565  -5.063983   1.437780   4.286887   5.105778 -1.244562  angry
9566  31.275461  -3.614327  -4.939654   1.536256 -7.109353  angry
9567  23.448828   0.456742  -4.137164  -0.131042 -2.212132  angry
9568  -9.774920 -10.505454 -12.224198  -4.848677  0.645746  angry
9569  29.665734  -0.822773  -4.105644   2.548632 -0.767205  angry
9570 -10.868347 -11.881487 -11.610377  -4.195009 -0.682545  angry
9571  -4.830352  -6.082828   7.277112  23.562659  2.881646  angry
9572 -10.006092  -5.706374  -8.418359  -4.659779 -2.542895  angry
9573  -9.718165  -8.613078  -7.405528  -3.304909 -1.417706  angry

In [9]:
#df = df[:2]

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x, y.ravel(), test_size=0.2, random_state=0)


from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier(max_depth=2, random_state=0)
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

In [10]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

cm = confusion_matrix(y_test, y_pred)
print(cm)
print('Accuracy' +str(accuracy_score(y_test, y_pred)))

[[ 25   0   3   0 294   0   0   0]
 [  0   0   0   0  15   0   0   0]
 [  0   0  65   0 344   0   0   0]
 [  6   0   0   0 109   0   0   0]
 [  0   0   7   0 856   0   0   0]
 [  0   0   0   0  56   0   0   0]
 [  0   0   0   0  30   0   0   0]
 [  4   0  25   0  76   0   0   0]]
Accuracy0.4939947780678851


In [11]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [12]:
from sklearn.decomposition import PCA

pca = PCA()
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)

cm = confusion_matrix(y_test, y_pred)
print(cm)
print('Accuracy' +str(accuracy_score(y_test, y_pred)))

[[ 25   0   3   0 294   0   0   0]
 [  0   0   0   0  15   0   0   0]
 [  0   0  65   0 344   0   0   0]
 [  6   0   0   0 109   0   0   0]
 [  0   0   7   0 856   0   0   0]
 [  0   0   0   0  56   0   0   0]
 [  0   0   0   0  30   0   0   0]
 [  4   0  25   0  76   0   0   0]]
Accuracy0.4939947780678851


In [13]:
from sklearn.pipeline import Pipeline
from sklearn.decomposition import PCA

finalDf.to_csv (base_path+'/exp-pca-features-casme-square-vgg16.csv', index = False, header=True)
