In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
import pandas as pd
import os

base_path = '/content/drive/MyDrive/final-cv-term/casme_square/densenet'
csvPath = os.path.sep.join([base_path,
  "{}.csv".format('test-exp-features-densenet_casme_suqare')])
#csvFile = open(csvPath, "w")

#writer = csv.writer(csvFile)
features_list = ['Label']
features_list.append('Image');
for i in range(1000):
  features_list.append('F' + str(i));

df = pd.read_csv(csvPath,names=features_list)
df = df.dropna(axis=0, how='any', thresh=None, subset=None, inplace=False)

In [5]:
df.head(5)

Label     Image        F0        F1  ...      F996      F997       F998      F999
0  happy  8065.jpg -5.192692 -3.800985  ...  0.070448 -4.562477   7.165855 -6.493895
1  happy  8498.jpg -2.696185 -1.322449  ...  3.721202 -2.143106  11.663564 -6.528202
2  happy  6122.jpg -2.175405  1.554681  ... -1.352250 -3.716215  12.473011 -8.514221
3  happy  7214.jpg -0.231902 -2.141334  ... -1.896002 -3.966842   3.402136 -8.236820
4  happy  4417.jpg  0.159632 -3.405606  ... -2.850278 -3.477453   8.884275 -4.922940

[5 rows x 1002 columns]

In [6]:
print(features_list)
print('after\n')
features_labels = features_list[2:]
print(features_labels)

['Label', 'Image', 'F0', 'F1', 'F2', 'F3', 'F4', 'F5', 'F6', 'F7', 'F8', 'F9', 'F10', 'F11', 'F12', 'F13', 'F14', 'F15', 'F16', 'F17', 'F18', 'F19', 'F20', 'F21', 'F22', 'F23', 'F24', 'F25', 'F26', 'F27', 'F28', 'F29', 'F30', 'F31', 'F32', 'F33', 'F34', 'F35', 'F36', 'F37', 'F38', 'F39', 'F40', 'F41', 'F42', 'F43', 'F44', 'F45', 'F46', 'F47', 'F48', 'F49', 'F50', 'F51', 'F52', 'F53', 'F54', 'F55', 'F56', 'F57', 'F58', 'F59', 'F60', 'F61', 'F62', 'F63', 'F64', 'F65', 'F66', 'F67', 'F68', 'F69', 'F70', 'F71', 'F72', 'F73', 'F74', 'F75', 'F76', 'F77', 'F78', 'F79', 'F80', 'F81', 'F82', 'F83', 'F84', 'F85', 'F86', 'F87', 'F88', 'F89', 'F90', 'F91', 'F92', 'F93', 'F94', 'F95', 'F96', 'F97', 'F98', 'F99', 'F100', 'F101', 'F102', 'F103', 'F104', 'F105', 'F106', 'F107', 'F108', 'F109', 'F110', 'F111', 'F112', 'F113', 'F114', 'F115', 'F116', 'F117', 'F118', 'F119', 'F120', 'F121', 'F122', 'F123', 'F124', 'F125', 'F126', 'F127', 'F128', 'F129', 'F130', 'F131', 'F132', 'F133', 'F134', 'F135', 'F1

In [7]:
print(df['Label'])

0       happy
1       happy
2       happy
3       happy
4       happy
        ...  
9569    angry
9570    angry
9571    angry
9572    angry
9573    angry
Name: Label, Length: 9574, dtype: object


In [8]:
from sklearn.preprocessing import StandardScaler

df2 = df[2:]
# Separating out the features
x = df.loc[:, features_labels].values
print(x)
# Separating out the target
y = df.loc[:,['Label']].values
# Standardizing the features
x = StandardScaler().fit_transform(x)


[[ -5.192692    -3.800985     0.6761545  ...  -4.562477     7.165855
   -6.493895  ]
 [ -2.6961854   -1.3224485    1.2549424  ...  -2.1431062   11.663564
   -6.5282016 ]
 [ -2.1754053    1.5546811    8.0663     ...  -3.7162151   12.473011
   -8.514221  ]
 ...
 [ -2.0069456   -3.7649598   -0.24194014 ... -10.051822     8.650379
   -6.3291454 ]
 [  1.6272377    0.37608838  -0.5905052  ...  -1.2840669    5.0648155
   -2.9084702 ]
 [  1.3167319    1.212243    -1.0428661  ...  -1.8186963    5.114124
   -3.1624165 ]]


In [9]:
from sklearn.decomposition import PCA
import numpy as np
pca = PCA(n_components=5)
principalComponents = pca.fit_transform(x)
principalDf = pd.DataFrame(data = principalComponents)

principalDf.reset_index(drop=True, inplace=True)
df['Label'].reset_index(drop=True, inplace=True)

finalDf = pd.concat([principalDf, df['Label']], axis=1)

finalDf.tail(20)

0          1          2          3          4  Label
9554 -13.748019  19.601788   2.173764  -6.752962  -7.977641  angry
9555  -8.862589 -11.815449   3.780063   9.129701  -1.822504  angry
9556  -7.136271  -2.917507 -23.557748  10.740581   5.783454  angry
9557  -6.772173 -13.038298   1.955135   3.198638  -4.861983  angry
9558  15.853886  -5.920775   0.145324   0.930221  -9.006755  angry
9559  -7.225248 -12.015626   3.452387   6.484785  -2.824817  angry
9560  -8.763012  -3.615522 -24.095232  11.504566   7.656336  angry
9561  15.790279  -7.676092  -3.770851  -1.948086  -6.611840  angry
9562   2.143526  -6.006494  -8.491374  -7.896531   3.856177  angry
9563 -13.128580  21.261884  -1.446661  -3.994356  -4.733985  angry
9564 -11.837913  14.842087  -3.240442  -6.814642  -4.579272  angry
9565   3.110350  -5.576372  -9.257079  -8.105898   3.904849  angry
9566 -15.746493  19.401139  -1.789384  -0.333613  -3.349877  angry
9567  -8.893917  20.113297   0.962181  -8.626962   1.203741  angry
9568  -8.072192 -13.484007   9.637265   5.327087  -6.143151  angry
9569 -11.881431  21.045946   3.085480  -7.246960  -7.862142  angry
9570  -7.998189 -14.364268  12.295471   5.339714  -6.514752  angry
9571  -1.146863  -5.524776  15.607972  -8.660954  19.338067  angry
9572  -3.895370 -14.105517  -5.132248  -2.050045  -8.202967  angry
9573  -4.640993 -13.956993  -4.651365  -2.057251  -8.449987  angry

In [10]:
#df = df[:2]

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)


from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier(max_depth=2, random_state=0)
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:11: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  # This is added back by InteractiveShellApp.init_path()


In [11]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

cm = confusion_matrix(y_test, y_pred)
print(cm)
print('Accuracy' +str(accuracy_score(y_test, y_pred)))

[[  0   0   0   0 322   0   0   0]
 [  0   0   0   0  15   0   0   0]
 [  0   0  36   0 373   0   0   0]
 [  0   0  12   0 103   0   0   0]
 [  0   0   0   0 863   0   0   0]
 [  0   0   0   0  56   0   0   0]
 [  0   0  10   0  20   0   0   0]
 [  0   0   0   0 105   0   0   0]]
Accuracy0.46945169712793733


In [12]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [13]:
from sklearn.decomposition import PCA

pca = PCA()
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)

cm = confusion_matrix(y_test, y_pred)
print(cm)
print('Accuracy' +str(accuracy_score(y_test, y_pred)))

[[  0   0   0   0 322   0   0   0]
 [  0   0   0   0  15   0   0   0]
 [  0   0  36   0 373   0   0   0]
 [  0   0  12   0 103   0   0   0]
 [  0   0   0   0 863   0   0   0]
 [  0   0   0   0  56   0   0   0]
 [  0   0  10   0  20   0   0   0]
 [  0   0   0   0 105   0   0   0]]
Accuracy0.46945169712793733


In [14]:
from sklearn.pipeline import Pipeline
from sklearn.decomposition import PCA

finalDf.to_csv (base_path+'/exp-pca-features-casme_suqare-densenet.csv', index = False, header=True)
